version: '3'

services:
    db:
        image: postgres:9.6.3
        environment:
            POSTGRES_DB: rappdb
            POSTGRES_USER: rails
            POSTGRES_PASS: pass88((
        volumes:
            - pgdata:/var/lib/postgresql/data

    web:
        build: .
        command: bundle exec rails s -p 3000 -b '0.0.0.0'
        environment:
            DB_HOST: db
            DB_NAME: rappdb
            DB_USERNAME: rails
            DB_PASSWORD: pass88((
        ports:
            - "3000:3000"
        volumes:
            - gems:/gems
            - .:/rapp
        depends_on:
            - db
volumes:
    pgdata:
        external: false
    gems:
        external: false

